use crate::mcp::registry::{ToolCost, ToolExposure, ToolSpec, ToolStability};
use crate::mcp::schemas::*;
use crate::tools::*;

pub const ANALYSIS_TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "import_export_inspect",
        description: "Extract import/export/module-use statements from source text using lightweight language-aware heuristics. Supports Rust, Python, JavaScript/TypeScript, and Go.",
        handler: import_export_inspect,
        input_schema: import_export_inspect_input,
        output_schema: import_export_inspect_output,
        category: "analysis",
        tier: 2,
        profiles: &["full", "codegg_core", "codegg_repo_audit"],
        tags: &["analysis", "imports", "exports", "source", "language"],
        exposure: ToolExposure::Contextual,
        harness_use: &[],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "code_block_map",
        description: "Return approximate top-level block ranges (functions, classes, modules, headings) from source text or Markdown. Helps agents target edits without full parsing.",
        handler: code_block_map,
        input_schema: code_block_map_input,
        output_schema: code_block_map_output,
        category: "analysis",
        tier: 2,
        profiles: &["full", "codegg_core", "codegg_repo_audit"],
        tags: &["analysis", "blocks", "structure", "source", "navigation"],
        exposure: ToolExposure::Contextual,
        harness_use: &[],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "symbol_name_diff",
        description: "Compare old/new source text and report added, removed, and possibly renamed top-level symbols using brace/indentation-based heuristics.",
        handler: symbol_name_diff,
        input_schema: symbol_name_diff_input,
        output_schema: symbol_name_diff_output,
        category: "analysis",
        tier: 2,
        profiles: &["full", "codegg_patch", "codegg_repo_audit"],
        tags: &["analysis", "symbols", "diff", "rename", "source"],
        exposure: ToolExposure::Contextual,
        harness_use: &[],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "lockfile_inspect",
        description: "Inspect lockfile content or diffs for deterministic dependency-change signals. Detects added/removed/updated packages, git/path dependencies, and large churn. Not a vulnerability scanner.",
        handler: lockfile_inspect,
        input_schema: lockfile_inspect_input,
        output_schema: lockfile_inspect_output,
        category: "analysis",
        tier: 2,
        profiles: &["full", "codegg_repo_audit", "codegg_patch", "codegg_preflight"],
        tags: &["lockfile", "dependency", "inspection", "changes", "security"],
        exposure: ToolExposure::Contextual,
        harness_use: &[],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
];
