use crate::mcp::registry::{ToolCost, ToolExposure, ToolSpec, ToolStability};
use crate::mcp::schemas::*;
use crate::tools::*;

pub const DIAGNOSTICS_TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "runtime_diagnostics",
        description: "Return structured runtime diagnostics including active profile, tool counts, budget tiers, and environment status. For harness/debug audiences only.",
        handler: runtime_diagnostics,
        input_schema: runtime_diagnostics_input,
        output_schema: runtime_diagnostics_output,
        category: "diagnostics",
        tier: 3,
        profiles: &["full"],
        tags: &["diagnostics", "runtime", "harness"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["runtime introspection", "diagnostics"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "profile_inspect",
        description: "Inspect a named profile: tool count, audience, purpose, route-critical presence, and representative tools. Use to understand what a profile is intended for.",
        handler: profile_inspect,
        input_schema: profile_inspect_input,
        output_schema: profile_inspect_output,
        category: "diagnostics",
        tier: 3,
        profiles: &["full"],
        tags: &["diagnostics", "profile", "harness"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["profile inspection", "debugging", "routing"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "tool_availability_explain",
        description: "Explain why a tool is or is not available in the active profile and audience. Returns existence, exposure, profiles, reason, and suggestions for close matches or correct profiles.",
        handler: tool_availability_explain,
        input_schema: tool_availability_explain_input,
        output_schema: tool_availability_explain_output,
        category: "diagnostics",
        tier: 3,
        profiles: &["full"],
        tags: &["diagnostics", "availability", "harness"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["tool debugging", "availability check", "missing tool diagnosis"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
];
