use crate::mcp::registry::{ToolCost, ToolExposure, ToolSpec, ToolStability};
use crate::mcp::schemas::*;
use crate::tools::*;

pub const IDENTIFIER_TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "identifier_analyze",
        description: "Classify and validate identifier naming conventions across languages.",
        handler: identifier_analyze,
        input_schema: identifier_analyze_input,
        output_schema: identifier_analyze_output,
        category: "identifier",
        tier: 3,
        profiles: &["full"],
        tags: &["text", "identifier", "naming", "validation", "language"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "identifier_inspect",
        description: "Inspect identifiers for validity and collisions. Detects confusables, mixed scripts, normalization issues, and casefold collisions across a list of identifiers.",
        handler: identifier_inspect,
        input_schema: identifier_inspect_input,
        output_schema: identifier_inspect_output,
        category: "identifier",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_unicode_security"],
        tags: &["text", "identifier", "collision", "confusable", "security", "validation"],
        exposure: ToolExposure::Default,
        harness_use: &["reasoning_only"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "identifier_table_inspect",
        description: "Inspect a table of identifiers for casefold collisions, normalization collisions, confusable/near-collisions, style variants, reserved keyword hits, and mixed naming style groups. Accepts structured entries with name, kind, file, and line metadata.",
        handler: identifier_table_inspect,
        input_schema: identifier_table_inspect_input,
        output_schema: identifier_table_inspect_output,
        category: "identifier",
        tier: 3,
        profiles: &["full", "codegg_repo_audit"],
        tags: &["text", "identifier", "collision", "naming", "style", "reserved", "validation"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["repo_audit"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
];
