use crate::mcp::registry::{ToolCost, ToolExposure, ToolSpec, ToolStability};
use crate::mcp::schemas::*;
use crate::tools::*;

pub const LIST_TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "list_compare",
        description: "Compare two lists with explicit modes: ordered ( LCS-based alignment), set (presence only), multiset (count deltas). Near matches are optional and never replace exact missing/extra results.",
        handler: list_compare,
        input_schema: list_compare_input,
        output_schema: list_compare_output,
        category: "list",
        tier: 2,
        profiles: &["full"],
        tags: &["text", "list", "comparison", "set"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "list_dedupe",
        description: "Remove duplicates from a list while preserving order. Supports Unicode normalization and casefolding.",
        handler: list_dedupe,
        input_schema: list_dedupe_input,
        output_schema: list_dedupe_output,
        category: "list",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["list", "dedupe", "unique", "normalization"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "list_sort",
        description: "Sort a list of strings with Unicode normalization and casefold support.",
        handler: list_sort,
        input_schema: list_sort_input,
        output_schema: list_sort_output,
        category: "list",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["list", "sort", "order", "normalization"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
];
