use crate::mcp::registry::{ToolCost, ToolExposure, ToolSpec, ToolStability};
use crate::mcp::schemas::*;
use crate::tools::*;

pub const VALIDATION_TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "validate_brackets",
        description: "Check whether delimiters are structurally balanced and report unmatched delimiters with line/column positions.",
        handler: validate_brackets,
        input_schema: validate_brackets_input,
        output_schema: validate_brackets_output,
        category: "validation",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["validation", "brackets", "delimiters"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_json",
        description: "Validate JSON and report precise parse errors or top-level structure information.",
        handler: validate_json,
        input_schema: validate_json_input,
        output_schema: validate_json_output,
        category: "validation",
        tier: 0,
        profiles: &["full", "default", "codegg_core", "codegg_core_min", "codegg_config"],
        tags: &["validation", "json", "structured-data"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_toml",
        description: "Validate TOML configuration files (Cargo.toml, pyproject.toml, etc.) and report parse errors with line/column positions.",
        handler: validate_toml_tool,
        input_schema: validate_toml_input,
        output_schema: validate_toml_output,
        category: "validation",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_config"],
        tags: &["validation", "structured-data", "toml", "config", "rust", "python"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_schema_light",
        description: "Validate JSON against a simple schema format with type, required, enum, pattern, and nested constraints.",
        handler: validate_schema_light_tool,
        input_schema: validate_schema_light_input,
        output_schema: validate_schema_light_output,
        category: "validation",
        tier: 3,
        profiles: &["full", "codegg_config"],
        tags: &["validation", "json", "schema", "structured-data"],
        exposure: ToolExposure::Contextual,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
];
