use super::types::{ToolCost, ToolExposure, ToolSpec, ToolStability};
use crate::mcp::schemas::*;
use crate::tools::*;

// ---------------------------------------------------------------------------
// Static registry
// ---------------------------------------------------------------------------

pub const ALL_TOOLS: &[ToolSpec] = &[
    ToolSpec {
        name: "math_eval",
        description: "Evaluate arithmetic, unit conversions, constants, and scientific expressions deterministically. State-mutating functions (setvar, store, etc.) and non-deterministic functions (random, randint, gauss, etc.) are disabled. Use for math and unit tasks instead of asking the model to calculate.",
        handler: math_eval,
        input_schema: math_eval_input,
        output_schema: math_eval_output,
        category: "math",
        tier: 0,
        profiles: &["full", "default", "human_math"],
        tags: &["math", "evaluation", "arithmetic", "units", "constants"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "unit_convert",
        description: "Convert a numeric value from one unit to another using pre-defined conversion factors.",
        handler: unit_convert,
        input_schema: unit_convert_input,
        output_schema: unit_convert_output,
        category: "math",
        tier: 2,
        profiles: &["full", "human_math"],
        tags: &["math", "units", "conversion"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "unit_info",
        description: "Get information about a unit including its canonical form and category.",
        handler: unit_info,
        input_schema: unit_info_input,
        output_schema: unit_info_output,
        category: "math",
        tier: 2,
        profiles: &["full", "human_math"],
        tags: &["math", "units", "information"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "constant_lookup",
        description: "Look up physical constant values and symbols (Avogadro, Planck, speed of light, etc.).",
        handler: constant_lookup,
        input_schema: constant_lookup_input,
        output_schema: constant_lookup_output,
        category: "math",
        tier: 2,
        profiles: &["full", "human_math"],
        tags: &["math", "constants", "physics", "lookup"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_measure",
        description: "Measure exact text properties: UTF-8 byte length, codepoint count, words, lines, whitespace, newline style, Unicode normalization state, invisibles, and mixed-script signals.",
        handler: text_measure,
        input_schema: text_measure_input,
        output_schema: text_measure_output,
        category: "text",
        tier: 0,
        profiles: &["full", "default"],
        tags: &["text", "measurement", "unicode", "metrics"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_equal",
        description: "Compare two strings under raw, Unicode-normalized, casefolded, or trimmed modes and report exact equality evidence.",
        handler: text_equal,
        input_schema: text_equal_input,
        output_schema: text_equal_output,
        category: "text",
        tier: 0,
        profiles: &["full", "default", "codegg_core"],
        tags: &["text", "comparison", "equality", "unicode"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_diff_explain",
        description: "Explain why two strings differ, including spans, codepoints, Unicode names, normalization equivalence, confusables, invisibles, and agent-facing classification.",
        handler: text_diff_explain,
        input_schema: text_diff_explain_input,
        output_schema: text_diff_explain_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_patch"],
        tags: &["text", "diff", "comparison", "unicode"],
        exposure: ToolExposure::Default,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_inspect",
        description: "Inspect a string for hidden characters, Unicode confusables, mixed scripts, normalization state, and display-safe representation. Can report both original and normalized text analysis.",
        handler: text_inspect,
        input_schema: text_inspect_input,
        output_schema: text_inspect_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_unicode_security"],
        tags: &["text", "unicode", "inspection", "security"],
        exposure: ToolExposure::Default,
        harness_use: &["prompt_input_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_count",
        description: "Count exact characters or produce a character frequency table with codepoint positions, grapheme clusters, bytes, or substring matches.",
        handler: text_count,
        input_schema: text_count_input,
        output_schema: text_count_output,
        category: "text",
        tier: 0,
        profiles: &["full", "default"],
        tags: &["text", "count", "character", "frequency"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_truncate",
        description: "Truncate a string to a specified number of grapheme clusters (user-perceived characters). Preserves emoji, combining sequences, and flag sequences intact. Useful for AI agent prompts where visual length matters.",
        handler: text_truncate,
        input_schema: text_truncate_input,
        output_schema: text_truncate_output,
        category: "text",
        tier: 3,
        profiles: &["full"],
        tags: &["text", "truncation", "grapheme", "unicode"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_transform",
        description: "Apply deterministic text transformations: Unicode normalization (NFC/NFD/NFKC/NFKD), casefold, trim, newline normalization, zero-width removal, bidi control stripping, and visible representation.",
        handler: text_transform,
        input_schema: text_transform_input,
        output_schema: text_transform_output,
        category: "text",
        tier: 2,
        profiles: &["full", "codegg_unicode_security"],
        tags: &["text", "unicode", "transform", "normalization", "sanitation"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_brackets",
        description: "Check whether delimiters are structurally balanced and report unmatched delimiters with line/column positions.",
        handler: validate_brackets,
        input_schema: validate_brackets_input,
        output_schema: validate_brackets_output,
        category: "validation",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["validation", "brackets", "delimiters"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_json",
        description: "Validate JSON and report precise parse errors or top-level structure information.",
        handler: validate_json,
        input_schema: validate_json_input,
        output_schema: validate_json_output,
        category: "validation",
        tier: 0,
        profiles: &["full", "default", "codegg_core", "codegg_core_min", "codegg_config"],
        tags: &["validation", "json", "structured-data"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_regex",
        description: "Test a Python regular expression against sample strings and report match/fullmatch status, spans, groups, and errors.",
        handler: validate_regex,
        input_schema: validate_regex_input,
        output_schema: validate_regex_output,
        category: "regex",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["text", "regex", "validation", "pattern"],
        exposure: ToolExposure::Default,
        harness_use: &["command_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "list_compare",
        description: "Compare two lists with explicit modes: ordered ( LCS-based alignment), set (presence only), multiset (count deltas). Near matches are optional and never replace exact missing/extra results.",
        handler: list_compare,
        input_schema: list_compare_input,
        output_schema: list_compare_output,
        category: "list",
        tier: 2,
        profiles: &["full"],
        tags: &["text", "list", "comparison", "set"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_toml",
        description: "Validate TOML configuration files (Cargo.toml, pyproject.toml, etc.) and report parse errors with line/column positions.",
        handler: validate_toml_tool,
        input_schema: validate_toml_input,
        output_schema: validate_toml_output,
        category: "validation",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_config"],
        tags: &["validation", "structured-data", "toml", "config", "rust", "python"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "json_extract",
        description: "Extract a value from JSON using RFC 6901 JSON Pointer (e.g., /foo/bar/0). Navigate nested objects and arrays.",
        handler: json_extract,
        input_schema: json_extract_input,
        output_schema: json_extract_output,
        category: "json",
        tier: 2,
        profiles: &["full", "codegg_config"],
        tags: &["json", "structured-data", "extraction", "config", "pointer"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "json_compare",
        description: "Compare two JSON documents semantically, ignoring formatting and key order.",
        handler: json_compare,
        input_schema: json_compare_input,
        output_schema: json_compare_output,
        category: "json",
        tier: 1,
        profiles: &["full", "default", "codegg_config"],
        tags: &["json", "structured-data", "comparison", "config"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_position",
        description: "Convert between byte offsets, codepoint indices, line/column positions, and UTF-16 offsets.",
        handler: text_position,
        input_schema: text_position_input,
        output_schema: text_position_output,
        category: "text",
        tier: 2,
        profiles: &["full", "codegg_unicode_security"],
        tags: &["text", "position", "offset", "unicode", "lsp"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_hash",
        description: "Compute cryptographic hashes of text for identity checking.",
        handler: text_hash,
        input_schema: text_hash_input,
        output_schema: text_hash_output,
        category: "text",
        tier: 2,
        profiles: &["full"],
        tags: &["text", "hash", "identity", "security"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "escape_text",
        description: "Escape text for various output formats.",
        handler: escape_text,
        input_schema: escape_text_input,
        output_schema: escape_text_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["text", "escape", "encoding", "shell", "json", "regex"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "unescape_text",
        description: "Unescape text from various formats.",
        handler: unescape_text,
        input_schema: unescape_text_input,
        output_schema: unescape_text_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["text", "escape", "encoding", "shell", "json", "regex"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "identifier_analyze",
        description: "Classify and validate identifier naming conventions across languages.",
        handler: identifier_analyze,
        input_schema: identifier_analyze_input,
        output_schema: identifier_analyze_output,
        category: "identifier",
        tier: 3,
        profiles: &["full"],
        tags: &["text", "identifier", "naming", "validation", "language"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "regex_finditer",
        description: "Find all regex matches in text with positions, line/column info, and capture groups.",
        handler: regex_finditer_tool,
        input_schema: regex_finditer_input,
        output_schema: regex_finditer_output,
        category: "regex",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["text", "regex", "search", "find", "pattern"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "regex_safety_check",
        description: "Heuristic check for potential catastrophic backtracking risks in regex patterns. Flags nested quantifiers, repeated alternations, ambiguous dot-star, and backreferences.",
        handler: regex_safety_check_tool,
        input_schema: regex_safety_check_input,
        output_schema: regex_safety_check_output,
        category: "regex",
        tier: 1,
        profiles: &["full", "default", "codegg_shell"],
        tags: &["text", "regex", "safety", "security", "backtracking"],
        exposure: ToolExposure::Default,
        harness_use: &["command_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "validate_schema_light",
        description: "Validate JSON against a simple schema format with type, required, enum, pattern, and nested constraints.",
        handler: validate_schema_light_tool,
        input_schema: validate_schema_light_input,
        output_schema: validate_schema_light_output,
        category: "validation",
        tier: 3,
        profiles: &["full", "codegg_config"],
        tags: &["validation", "json", "schema", "structured-data"],
        exposure: ToolExposure::Contextual,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "path_normalize",
        description: "Normalize a path using posixpath or ntpath semantics. Collapse dot segments, resolve components.",
        handler: path_normalize_tool,
        input_schema: path_normalize_input,
        output_schema: path_normalize_output,
        category: "path",
        tier: 0,
        profiles: &["full", "default", "codegg_core"],
        tags: &["text", "path", "filesystem", "normalize"],
        exposure: ToolExposure::Default,
        harness_use: &["path_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "path_analyze",
        description: "Analyze path components, extensions, hidden status, and traversal without filesystem access.",
        handler: path_analyze,
        input_schema: path_analyze_input,
        output_schema: path_analyze_output,
        category: "path",
        tier: 2,
        profiles: &["full"],
        tags: &["text", "path", "filesystem", "lexical"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "path_compare",
        description: "Compare two paths under explicit normalization rules: separator normalization, dot-segment collapsing, and optional case-insensitive comparison.",
        handler: path_compare,
        input_schema: path_compare_input,
        output_schema: path_compare_output,
        category: "path",
        tier: 2,
        profiles: &["full"],
        tags: &["text", "path", "filesystem", "comparison"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "path_scope_check",
        description: "Determine whether a target path remains lexically inside a declared root. Lexical only, does not resolve symlinks.",
        handler: path_scope_check,
        input_schema: path_scope_check_input,
        output_schema: path_scope_check_output,
        category: "path",
        tier: 2,
        profiles: &["full", "codegg_preflight"],
        tags: &["text", "path", "filesystem", "security", "scope"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["path_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "json_shape",
        description: "Analyze the structure of a JSON document without returning values. Shows type, keys, and nested structure with configurable depth limits.",
        handler: json_shape_tool,
        input_schema: json_shape_input,
        output_schema: json_shape_output,
        category: "json",
        tier: 3,
        profiles: &["full", "codegg_repo_audit"],
        tags: &["json", "structured-data", "shape", "schema"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_window",
        description: "Get a window around a position in text with context lines. Shows line at position with surrounding context, position metrics, and character details.",
        handler: text_window,
        input_schema: text_window_input,
        output_schema: text_window_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["text", "position", "context", "unicode", "window"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "json_canonicalize",
        description: "Canonicalize JSON with deterministic formatting, key ordering, duplicate key detection, and stable hashes.",
        handler: json_canonicalize,
        input_schema: json_canonicalize_input,
        output_schema: json_canonicalize_output,
        category: "json",
        tier: 1,
        profiles: &["full", "default", "codegg_config"],
        tags: &["json", "canonical", "hash", "deterministic", "format"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "json_query",
        description: "Extract a value from JSON using RFC 6901 JSON Pointer. Navigate nested objects and arrays. Deprecated: use json_extract instead, which provides richer output including available_keys, missing_at, and detail levels.",
        handler: json_query,
        input_schema: json_query_input,
        output_schema: json_query_output,
        category: "json",
        tier: 1,
        profiles: &["full"],
        tags: &["json", "pointer", "extraction", "query", "rfc6901"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Deprecated,
        composite: false,
    },
    ToolSpec {
        name: "glob_match",
        description: "Match a glob pattern against a path with explicit semantics: * matches within one segment, ** matches zero or more segments, ? matches one char. Python fnmatch limitations around ** are documented.",
        handler: glob_match_tool,
        input_schema: glob_match_input,
        output_schema: glob_match_output,
        category: "path",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["text", "glob", "pattern", "path", "wildcard"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_fingerprint",
        description: "Compute a deterministic SHA-256 fingerprint of text with canonicalization options for Unicode normalization, newline style, casefold, and final newline trimming.",
        handler: text_fingerprint_tool,
        input_schema: text_fingerprint_input,
        output_schema: text_fingerprint_output,
        category: "text",
        tier: 0,
        profiles: &["full", "default", "codegg_core", "codegg_repo_audit"],
        tags: &["text", "hash", "fingerprint", "sha256", "identity", "canonicalization"],
        exposure: ToolExposure::Default,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "identifier_inspect",
        description: "Inspect identifiers for validity and collisions. Detects confusables, mixed scripts, normalization issues, and casefold collisions across a list of identifiers.",
        handler: identifier_inspect,
        input_schema: identifier_inspect_input,
        output_schema: identifier_inspect_output,
        category: "identifier",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_unicode_security"],
        tags: &["text", "identifier", "collision", "confusable", "security", "validation"],
        exposure: ToolExposure::Default,
        harness_use: &["reasoning_only"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "version_compare",
        description: "Compare two version strings with explicit scheme. Supports semver (major.minor.patch), loose (numeric parts), and deferred pep440.",
        handler: version_compare_tool,
        input_schema: version_compare_input,
        output_schema: version_compare_output,
        category: "version",
        tier: 2,
        profiles: &["full", "codegg_config"],
        tags: &["version", "semver", "comparison"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "toml_shape",
        description: "Analyze the structure of a TOML document: top-level keys, tables, and nesting hierarchy.",
        handler: toml_shape_tool,
        input_schema: toml_shape_input,
        output_schema: toml_shape_output,
        category: "toml",
        tier: 2,
        profiles: &["full", "codegg_config"],
        tags: &["toml", "structure", "shape", "config", "validation"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "list_dedupe",
        description: "Remove duplicates from a list while preserving order. Supports Unicode normalization and casefolding.",
        handler: list_dedupe,
        input_schema: list_dedupe_input,
        output_schema: list_dedupe_output,
        category: "list",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["list", "dedupe", "unique", "normalization"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "list_sort",
        description: "Sort a list of strings with Unicode normalization and casefold support.",
        handler: list_sort,
        input_schema: list_sort_input,
        output_schema: list_sort_output,
        category: "list",
        tier: 1,
        profiles: &["full", "default"],
        tags: &["list", "sort", "order", "normalization"],
        exposure: ToolExposure::Default,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_replace_check",
        description: "Check whether a text replacement would apply cleanly before an agent attempts to edit. Reports match count, positions, ambiguity, and optional preview of before/after.",
        handler: text_replace_check_tool,
        input_schema: text_replace_check_input,
        output_schema: text_replace_check_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default", "codegg_core", "codegg_core_min", "codegg_patch"],
        tags: &["text", "replace", "edit", "safety", "check"],
        exposure: ToolExposure::Default,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "line_range_extract",
        description: "Extract exact line ranges from text and return stable offsets, byte positions, line counts, and optional fingerprint.",
        handler: line_range_extract_tool,
        input_schema: line_range_extract_input,
        output_schema: line_range_extract_output,
        category: "text",
        tier: 1,
        profiles: &["full", "default", "codegg_patch"],
        tags: &["text", "line", "range", "extract", "offset"],
        exposure: ToolExposure::Default,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "line_range_compare",
        description: "Compare a line range from two text inputs with exact, trailing-whitespace-ignoring, or newline-normalizing comparison.",
        handler: line_range_compare_tool,
        input_schema: line_range_compare_input,
        output_schema: line_range_compare_output,
        category: "text",
        tier: 2,
        profiles: &["full", "codegg_patch"],
        tags: &["text", "line", "range", "compare", "diff"],
        exposure: ToolExposure::Contextual,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "shell_split",
        description: "Parse a shell-like command string into argv tokens and report risky lexical features (pipes, redirections, command substitution, variable expansion, globs, control operators). Lexical POSIX-like parsing only, not full shell evaluation.",
        handler: shell_split,
        input_schema: shell_split_input,
        output_schema: shell_split_output,
        category: "shell",
        tier: 2,
        profiles: &["full", "codegg_preflight", "codegg_shell"],
        tags: &["shell", "argv", "parsing", "security", "sanity"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["command_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "shell_quote_join",
        description: "Safely quote a list of argv tokens into a POSIX-like shell string. Verifies round-trip safety with shell_split.",
        handler: shell_quote_join,
        input_schema: shell_quote_join_input,
        output_schema: shell_quote_join_output,
        category: "shell",
        tier: 2,
        profiles: &["full", "codegg_shell"],
        tags: &["shell", "argv", "quoting", "safety"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "argv_compare",
        description: "Compare two command strings or argv lists by parsed argv tokens rather than raw text. Supports command strings, pre-parsed argv lists, or both.",
        handler: argv_compare,
        input_schema: argv_compare_input,
        output_schema: argv_compare_output,
        category: "shell",
        tier: 2,
        profiles: &["full", "codegg_shell"],
        tags: &["shell", "argv", "comparison", "sanity"],
        exposure: ToolExposure::Contextual,
        harness_use: &["command_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "markdown_structure",
        description: "Parse Markdown structure with a deterministic line scanner: headings (level, text, slug), code fences (language, open/close state), links (visible vs target mismatch), HTML comments, frontmatter detection, and table detection. Not a full CommonMark parser.",
        handler: markdown_structure,
        input_schema: markdown_structure_input,
        output_schema: markdown_structure_output,
        category: "markdown",
        tier: 2,
        profiles: &["full", "codegg_repo_audit"],
        tags: &["markdown", "structure", "headings", "code-fences", "links", "frontmatter"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "code_fence_extract",
        description: "Extract fenced code blocks from Markdown with exact line ranges, optional language filter, content, and SHA-256 fingerprints. Reports unclosed fences.",
        handler: code_fence_extract,
        input_schema: code_fence_extract_input,
        output_schema: code_fence_extract_output,
        category: "markdown",
        tier: 2,
        profiles: &["full", "codegg_repo_audit"],
        tags: &["markdown", "code-fences", "extraction", "fingerprint"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "dotenv_validate",
        description: "Validate .env-style key=value configuration text. Detects invalid keys, duplicate keys, missing quotes, and variable expansion syntax. Line-by-line parser, no shell evaluation.",
        handler: dotenv_validate,
        input_schema: dotenv_validate_input,
        output_schema: dotenv_validate_output,
        category: "config",
        tier: 2,
        profiles: &["full", "codegg_config"],
        tags: &["validation", "config", "env", "dotenv"],
        exposure: ToolExposure::Contextual,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "ini_validate",
        description: "Validate simple INI-style configuration files. Supports [section] headers, key=value and key:value lines, comments. Detects duplicate sections, duplicate keys, and malformed lines.",
        handler: ini_validate,
        input_schema: ini_validate_input,
        output_schema: ini_validate_output,
        category: "config",
        tier: 2,
        profiles: &["full", "codegg_config"],
        tags: &["validation", "config", "ini"],
        exposure: ToolExposure::Contextual,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "patch_apply_check",
        description: "Validate and simulate a unified diff against provided in-memory files/text without touching the filesystem. Reports parse status, application success, failed hunks with context, and optional result fingerprint.",
        handler: patch_apply_check,
        input_schema: patch_apply_check_input,
        output_schema: patch_apply_check_output,
        category: "patch",
        tier: 2,
        profiles: &["full", "codegg_preflight", "codegg_patch"],
        tags: &["patch", "diff", "unified", "validation", "apply"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "patch_summary",
        description: "Summarize a unified diff without applying it. Reports file counts, hunk counts, additions, deletions, renames, and line ranges by file.",
        handler: patch_summary,
        input_schema: patch_summary_input,
        output_schema: patch_summary_output,
        category: "patch",
        tier: 2,
        profiles: &["full", "codegg_patch"],
        tags: &["patch", "diff", "unified", "summary", "statistics"],
        exposure: ToolExposure::Contextual,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "unicode_policy_check",
        description: "Apply a named deterministic Unicode safety policy to input text. Policies include identifier_strict (mixed scripts, bidi, confusables), filename_safe (control chars, path separators, reserved names), source_code, human_text (warn-only), json_key, and domain_like.",
        handler: unicode_policy_check,
        input_schema: unicode_policy_check_input,
        output_schema: unicode_policy_check_output,
        category: "unicode",
        tier: 2,
        profiles: &["full", "codegg_preflight", "codegg_unicode_security"],
        tags: &["text", "unicode", "policy", "security", "validation"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["prompt_input_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "canonicalize_text",
        description: "Apply a named text canonicalization profile. Profiles include source_file_identity (NFC + LF + newline), identifier_compare (NFC + casefold), human_label_compare (NFC + casefold + whitespace collapse), json_key_compare (NFC + casefold), and path_segment_compare (NFC + lowercase + LF).",
        handler: canonicalize_text,
        input_schema: canonicalize_text_input,
        output_schema: canonicalize_text_output,
        category: "unicode",
        tier: 2,
        profiles: &["full", "codegg_unicode_security"],
        tags: &["text", "unicode", "canonicalization", "normalization", "identity"],
        exposure: ToolExposure::Contextual,
        harness_use: &["prompt_input_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "identifier_table_inspect",
        description: "Inspect a table of identifiers for casefold collisions, normalization collisions, confusable/near-collisions, style variants, reserved keyword hits, and mixed naming style groups. Accepts structured entries with name, kind, file, and line metadata.",
        handler: identifier_table_inspect,
        input_schema: identifier_table_inspect_input,
        output_schema: identifier_table_inspect_output,
        category: "identifier",
        tier: 3,
        profiles: &["full", "codegg_repo_audit"],
        tags: &["text", "identifier", "collision", "naming", "style", "reserved", "validation"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["repo_audit"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "version_constraint_check",
        description: "Check whether a version satisfies a constraint under a declared versioning scheme (semver or cargo). Supports comparison operators, caret, tilde, wildcard, range, and comma-separated constraints.",
        handler: version_constraint_check,
        input_schema: version_constraint_check_input,
        output_schema: version_constraint_check_output,
        category: "version",
        tier: 3,
        profiles: &["full"],
        tags: &["version", "semver", "cargo", "constraint", "satisfiability"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["none"],
        aliases: &[],
        cost: ToolCost::Cheap,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "cargo_toml_inspect",
        description: "Inspect Cargo.toml text without network or filesystem access. Reports package metadata, workspace configuration, dependency forms (version/path/git/workspace), path dependencies, suspicious or confusable dependency names, and structural findings.",
        handler: cargo_toml_inspect,
        input_schema: cargo_toml_inspect_input,
        output_schema: cargo_toml_inspect_output,
        category: "cargo",
        tier: 3,
        profiles: &["full", "codegg_core", "codegg_repo_audit"],
        tags: &["rust", "cargo", "toml", "dependencies", "workspace", "inspection"],
        exposure: ToolExposure::ExpertOnly,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "prompt_input_inspect",
        description: "Deterministically inspect text for red flags that may influence agents or humans unexpectedly. Detects hidden Unicode characters, bidirectional controls, HTML comments, Markdown link mismatches, ANSI escapes, terminal controls, base64-like blobs, instruction-like phrases, and very long minified lines. This is NOT a prompt-injection detector -- it reports observable features only, not intent.",
        handler: prompt_input_inspect_tool,
        input_schema: prompt_input_inspect_input,
        output_schema: prompt_input_inspect_output,
        category: "text",
        tier: 2,
        profiles: &["full", "codegg_unicode_security", "codegg_preflight"],
        tags: &["text", "security", "inspection", "prompt", "unicode", "hidden"],
        exposure: ToolExposure::HarnessOnly,
        harness_use: &["prompt_input_preflight"],
        aliases: &[],
        cost: ToolCost::Moderate,
        stability: ToolStability::Stable,
        composite: false,
    },
    ToolSpec {
        name: "text_security_inspect",
        description: "Composite security-oriented text hygiene pass. Runs text_inspect, unicode_policy_check, canonicalize_text, prompt_input_inspect, and identifier_inspect depending on policy. Returns a verdict (allow/review/block) plus structured findings and machine codes.",
        handler: text_security_inspect,
        input_schema: text_security_inspect_input,
        output_schema: text_security_inspect_output,
        category: "text",
        tier: 1,
        profiles: &["full", "codegg_core", "codegg_core_min", "codegg_preflight", "codegg_unicode_security"],
        tags: &["text", "unicode", "security", "composite", "prompt", "inspection"],
        exposure: ToolExposure::Default,
        harness_use: &["prompt_input_preflight"],
        aliases: &[],
        cost: ToolCost::Heavy,
        stability: ToolStability::Stable,
        composite: true,
    },
    ToolSpec {
        name: "edit_preflight",
        description: "Composite: validate a proposed edit before applying it. Calls text_replace_check, patch_apply_check, line_range_extract, text_fingerprint, and text_diff_explain as needed. Returns ok_to_apply verdict with findings and machine codes.",
        handler: edit_preflight,
        input_schema: edit_preflight_input,
        output_schema: edit_preflight_output,
        category: "patch",
        tier: 1,
        profiles: &["full", "codegg_core", "codegg_core_min", "codegg_preflight", "codegg_patch"],
        tags: &["patch", "edit", "preflight", "composite", "text"],
        exposure: ToolExposure::Default,
        harness_use: &["edit_preflight"],
        aliases: &[],
        cost: ToolCost::Heavy,
        stability: ToolStability::Stable,
        composite: true,
    },
    ToolSpec {
        name: "command_preflight",
        description: "Composite: analyze a command before user approval or execution. Calls shell_split and regex_safety_check. Returns parsed argv, shell operators, risk findings, and a verdict. Must not execute anything.",
        handler: command_preflight,
        input_schema: command_preflight_input,
        output_schema: command_preflight_output,
        category: "shell",
        tier: 1,
        profiles: &["full", "codegg_core", "codegg_core_min", "codegg_preflight", "codegg_shell"],
        tags: &["shell", "command", "preflight", "composite", "security"],
        exposure: ToolExposure::Default,
        harness_use: &["command_preflight"],
        aliases: &[],
        cost: ToolCost::Heavy,
        stability: ToolStability::Stable,
        composite: true,
    },
    ToolSpec {
        name: "config_preflight",
        description: "Composite: validate generated config text. Auto-detects format and runs the appropriate validator. Returns valid/invalid, detected format, parse error location, and machine code.",
        handler: config_preflight,
        input_schema: config_preflight_input,
        output_schema: config_preflight_output,
        category: "config",
        tier: 1,
        profiles: &["full", "codegg_core", "codegg_core_min", "codegg_preflight", "codegg_config"],
        tags: &["config", "validation", "json", "toml", "preflight", "composite"],
        exposure: ToolExposure::Default,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Heavy,
        stability: ToolStability::Stable,
        composite: true,
    },
    ToolSpec {
        name: "structured_data_compare",
        description: "Composite: compare structured config/data output. Calls json_compare, json_canonicalize, and json_shape. Returns equal/not-equal verdict with structured diffs.",
        handler: structured_data_compare,
        input_schema: structured_data_compare_input,
        output_schema: structured_data_compare_output,
        category: "json",
        tier: 2,
        profiles: &["full", "codegg_core", "codegg_config"],
        tags: &["json", "comparison", "config", "structured-data", "composite"],
        exposure: ToolExposure::Contextual,
        harness_use: &["config_preflight"],
        aliases: &[],
        cost: ToolCost::Heavy,
        stability: ToolStability::Stable,
        composite: true,
    },
];

// ---------------------------------------------------------------------------
// Profile constants
// ---------------------------------------------------------------------------

pub const PROFILE_NAMES: &[&str] = &[
    "full",
    "default",
    "codegg_core_min",
    "codegg_core",
    "codegg_preflight",
    "codegg_patch",
    "codegg_config",
    "codegg_unicode_security",
    "codegg_shell",
    "codegg_repo_audit",
    "human_math",
];
